### ISSUE TITLE
Wrong Cron format?

### ISSUE THREAD

**Issue by filipre** [rainder/human-to-cron#2]
I'm kinda confused by the format that human-to-cron returns. 

```
humanToCron('friday 15:44') // => 0 44 15 4 * *
humanToCron('august friday 15:44') // => 0 44 15 4 7 *
```

I assume that the `4` / 4th position stands for Friday / day of week.

However, [Wikipedia](https://en.wikipedia.org/wiki/Cron#Configuration_file) describes a different format
```
 # * * * * *  command to execute
 # │ │ │ │ │
 # │ │ │ │ │
 # │ │ │ │ └───── day of week (0 - 6) (0 to 6 are Sunday to Saturday, or use names; 7 is Sunday, the same as 0)
 # │ │ │ └────────── month (1 - 12)
 # │ │ └─────────────── day of month (1 - 31)
 # │ └──────────────────── hour (0 - 23)
 # └───────────────────────── min (0 - 59)
```

where the day of week is on the last position. Furthermore it says that Friday should be `5` instead of a `4` because it starts with a `0` on Sunday. 
(Please ignore that seconds are missing in this example.)

**Comment by filipre** [comment]
I opened a PR in #3

**Comment by fenwick67** [comment]
PR was merged so should this be closed?
